# Generated by Django 4.2.6 on 2023-10-17 03:02

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('userID', models.IntegerField(blank=True, null=True)),
                ('embassadorID', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, choices=[('ACRE', 'Acre'), ('ALAGOAS', 'Alagoas'), ('AMAPA', 'Amapá'), ('AMAZONAS', 'Amazonas'), ('BAHIA', 'Bahia'), ('CEARA', 'Ceará'), ('DISTRITO_FEDERAL', 'Distrito Federal'), ('ESPIRITO_SANTO', 'Espírito Santo'), ('GOIAS', 'Goiás'), ('MARANHAO', 'Maranhão'), ('MATO_GROSSO', 'Mato Grosso'), ('MATO_GROSSO_DO_SUL', 'Mato Grosso do Sul'), ('MINAS_GERAIS', 'Minas Gerais'), ('PARA', 'Pará'), ('PARAIBA', 'Paraíba'), ('PARANA', 'Paraná'), ('PERNAMBUCO', 'Pernambuco'), ('PIAUI', 'Piauí'), ('RIO_DE_JANEIRO', 'Rio de Janeiro'), ('RIO_GRANDE_DO_NORTE', 'Rio Grande do Norte'), ('RIO_GRANDE_DO_SUL', 'Rio Grande do Sul'), ('RONDONIA', 'Rondônia'), ('RORAIMA', 'Roraima'), ('SANTA_CATARINA', 'Santa Catarina'), ('SAO_PAULO', 'São Paulo'), ('SERGIPE', 'Sergipe'), ('TOCANTINS', 'Tocantins')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('REJECTED', 'Rejected'), ('LOOKING_FOR_DONORS', 'Looking for donors'), ('IN_ANALISYS', 'In analisys'), ('APPROVED', 'Approved'), ('DONORS_FOUND', 'Donors found'), ('EXITED', 'Exited'), ('CONCLUDED', 'Concluded'), ('DEACTIVATED', 'Deactivated')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Ambassador'), (3, 'User')], null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, choices=[('ACRE', 'Acre'), ('ALAGOAS', 'Alagoas'), ('AMAPA', 'Amapá'), ('AMAZONAS', 'Amazonas'), ('BAHIA', 'Bahia'), ('CEARA', 'Ceará'), ('DISTRITO_FEDERAL', 'Distrito Federal'), ('ESPIRITO_SANTO', 'Espírito Santo'), ('GOIAS', 'Goiás'), ('MARANHAO', 'Maranhão'), ('MATO_GROSSO', 'Mato Grosso'), ('MATO_GROSSO_DO_SUL', 'Mato Grosso do Sul'), ('MINAS_GERAIS', 'Minas Gerais'), ('PARA', 'Pará'), ('PARAIBA', 'Paraíba'), ('PARANA', 'Paraná'), ('PERNAMBUCO', 'Pernambuco'), ('PIAUI', 'Piauí'), ('RIO_DE_JANEIRO', 'Rio de Janeiro'), ('RIO_GRANDE_DO_NORTE', 'Rio Grande do Norte'), ('RIO_GRANDE_DO_SUL', 'Rio Grande do Sul'), ('RONDONIA', 'Rondônia'), ('RORAIMA', 'Roraima'), ('SANTA_CATARINA', 'Santa Catarina'), ('SAO_PAULO', 'São Paulo'), ('SERGIPE', 'Sergipe'), ('TOCANTINS', 'Tocantins')], max_length=50, null=True)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
