# Generated by Django 4.2.6 on 2023-11-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='objective',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
