# Generated by Django 4.2.6 on 2023-11-16 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fullapp', '0002_user_objective_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Looking for donors', 'Looking for donors'), ('In analisys', 'In analisys'), ('Approved', 'Approved'), ('Donors found', 'Donors found'), ('Exited', 'Exited'), ('Concluded', 'Concluded'), ('Deactivated', 'Deactivated')], default='In analisys', max_length=255, null=True),
        ),
    ]
