# Generated by Django 4.2.6 on 2023-11-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullapp', '0004_alter_demand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(blank=True, choices=[('Reprovado', 'Reprovado'), ('Buscando Doadores', 'Buscando Doadores'), ('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Doador Atribuido', 'Doador Atribuido'), ('Em negociação', 'Em negociação'), ('Cancelado', 'Cancelado'), ('Concluido', 'Concluido'), ('Desativado', 'Desativado')], default='Em análise', max_length=255, null=True),
        ),
    ]
